# Home Assistant Configuration
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.0.0.0/8
  ip_ban_enabled: false

# Basic configuration
homeassistant:
  name: Home
  unit_system: metric
  time_zone: Europe/Madrid
  external_url: https://ha.palonso-pi.duckdns.org
